baseURL = '/'
publishDir = "dist"
defaultContentLanguage = "en"
title = "gnops"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
summaryLength = 10
uglyURLs = false
      
[Social]
    twitter = ""