[en]
    weight = 1
    contentDir = "content/english"
    languageName = "English"
    [en.params]
        slogan = "educational and community platform for gnomes"
        description = "Official website of gnops"
        siteTitle = "Official website of gnops"
        siteDescription = "Official website of gnops description"
        twitter = "https://twitter.com/gnome"
        github = "https://github.com/gnome"
